name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  build-linux:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: 'Upload Linux Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: linux-artifact
        path: ./target/release/btwn
        retention-days: 5
  build-windows:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-cross
      run: cargo install cross
    - name: Build for windows
      run: cross build --target=x86_64-pc-windows-gnu --release
    - name: 'Upload Windows Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: windows-artifact
        path: ./target/x86_64-pc-windows-gnu/release/btwn.exe
        retention-days: 5
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login
      run: cargo login ${{ secrets.CRATES_API_KEY }}
    - name: Publish
      run: cargo publish --allow-dirty
  release:
    needs:
      - build-linux
      - build-windows
    runs-on: ubuntu-latest  
    steps:
    - name: Download a linux artifact
      uses: actions/download-artifact@v3
      with:
        name: linux-artifact
    - name: Download a windows artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-artifact
    - name: Create Github release
      run: ./scripts/create_release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
