name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: cargo build --release
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      run: cargo login ${{ secrets.CRATES_API_KEY }}
    - name: Publish
      run: cargo publish --allow-dirty
  release:
    runs-on: ubuntu-latest  
    steps:
    - name: Install cargo-cross
      run: cargo install cross
    - name: Build for windows
      run: cross build --target=x86_64-pc-windows-gnu --release
    - name: Create Github release
      run: ./scripts/create_release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
